package main

import (
	"fmt"
	"net/http"
)

// This file demonstrates how to use the compiled GoX components
// After running: goxc build -o . TodoApp.gox
// This will use the generated TodoApp.go file

func main() {
	http.HandleFunc("/", handleHome)
	http.HandleFunc("/static/", handleStatic)

	fmt.Println("GoX Todo App Server")
	fmt.Println("Starting server on http://localhost:8080")

	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		fmt.Printf("Server error: %v\n", err)
	}
}

func handleHome(w http.ResponseWriter, r *http.Request) {
	// Create the TodoApp component
	// This function will be generated by the transpiler
	// app := NewTodoApp()

	// For now, serve a static HTML page
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoX Todo App</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
    </style>
</head>
<body>
    <div id="root">
        <!-- Component HTML will be rendered here -->
        <div class="todo-app">
            <h1>📝 Todo App</h1>
            <p style="text-align: center; color: #666;">
                Build this with: goxc build TodoApp.gox
            </p>
        </div>
    </div>
</body>
</html>`

	w.Header().Set("Content-Type", "text/html")
	fmt.Fprint(w, html)
}

func handleStatic(w http.ResponseWriter, r *http.Request) {
	// Serve static files (CSS, JS, etc.)
	http.ServeFile(w, r, r.URL.Path[1:])
}