//go:build js && wasm

package main

import (
	"syscall/js"
	// "gox/runtime/wasm"
)

// This would be auto-generated by goxc from Counter.gox
// For demonstration purposes, showing what the WASM entry point would look like

func main() {
	println("🚀 GoX WASM app starting...")

	// Get root element
	document := js.Global().Get("document")
	root := document.Call("getElementById", "root")

	if root.IsNull() {
		println("❌ Error: #root element not found")
		return
	}

	// Create counter component
	counter := NewCounter(0)

	// TODO: This would use the actual reconciler when implemented
	// reconciler := wasm.NewReconciler(counter, root)
	// reconciler.Mount()

	// For now, demonstrate the concept
	println("✅ Counter component created")
	println("Initial count:", 0)

	// Keep the program running
	select {}
}
