package main

import (
	"fmt"
	"log"
	"net/http"
)

// This would be auto-generated by goxc from Counter.gox
// For demonstration purposes, showing what the output would look like

func main() {
	http.HandleFunc("/", handleIndex)
	http.HandleFunc("/styles.css", handleStyles)

	port := ":8080"
	fmt.Printf("🚀 Server running on http://localhost%s\n", port)
	log.Fatal(http.ListenAndServe(port, nil))
}

func handleIndex(w http.ResponseWriter, r *http.Request) {
	// Create counter component with initial value
	counter := NewCounter(0)

	// Render component to HTML
	html := renderPage(counter.Render())

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, html)
}

func handleStyles(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/css; charset=utf-8")
	fmt.Fprint(w, generatedStyles)
}

func renderPage(content string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoX Counter - SSR Example</title>
    <link rel="stylesheet" href="/styles.css">
    <style>
        body {
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);
            min-height: 100vh;
        }
    </style>
</head>
<body>
    <div id="app">
        %s
    </div>

    <script>
        // Client-side hydration would go here
        // For now, this is a static render
    </script>
</body>
</html>`, content)
}

// This would be auto-generated CSS from the style block
const generatedStyles = `
/* Generated by GoX from Counter.gox */
.counter-container[data-gox-counter] {
    max-width: 400px;
    margin: 50px auto;
    padding: 30px;
    background: #f8f9fa;
    border-radius: 12px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.counter-display[data-gox-counter] {
    text-align: center;
    margin-bottom: 30px;
}

.counter-display[data-gox-counter] h1 {
    color: #333;
    margin: 0 0 20px 0;
    font-size: 28px;
}

.count-value[data-gox-counter] {
    font-size: 72px;
    font-weight: bold;
    color: #007bff;
    margin: 20px 0;
}

.counter-controls[data-gox-counter] {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-bottom: 20px;
}

.btn[data-gox-counter] {
    padding: 12px 24px;
    font-size: 16px;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.2s;
}

.btn[data-gox-counter]:hover {
    transform: translateY(-2px);
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}

.btn[data-gox-counter]:active {
    transform: translateY(0);
}

.btn-primary[data-gox-counter] {
    background: #007bff;
    color: white;
}

.btn-primary[data-gox-counter]:hover {
    background: #0056b3;
}

.btn-secondary[data-gox-counter] {
    background: #6c757d;
    color: white;
}

.btn-secondary[data-gox-counter]:hover {
    background: #545b62;
}

.btn-danger[data-gox-counter] {
    background: #dc3545;
    color: white;
}

.btn-danger[data-gox-counter]:hover {
    background: #c82333;
}

.counter-info[data-gox-counter] {
    background: white;
    padding: 15px;
    border-radius: 6px;
    font-size: 14px;
    color: #666;
}

.counter-info[data-gox-counter] p {
    margin: 5px 0;
}
`
