#!/bin/bash
# Pre-write validation hook
# Prevents writing to protected files

# Check if writing to protected files
if echo "$TOOL_INPUT" | grep -qE '(\.env|credentials\.json|secrets\.yaml)'; then
    echo "❌ ERROR: Cannot write to protected file (contains secrets)"
    exit 1
fi

# Check if writing to generated files without confirmation
if echo "$TOOL_INPUT" | grep -qE 'dist/.*\.go'; then
    echo "⚠️  WARNING: Writing to generated file in dist/"
    echo "These files are typically auto-generated by goxc"
    # Don't block, just warn
fi

# Success
exit 0
